### ISSUE TITLE
use this in the browser and sync with server

### ISSUE THREAD

**Issue by sethvincent** [sethvincent/level-model#3]
make sure that works

**Comment by BenjaminVerble** [comment]
I have usually used multilevel with leveldb, so my initial thought would be to simply use an isomorphic/ universal fetch / request library that would work on node and browser. But this is an intriguing idea. Perhaps the front-end models would check for env, use http in browser, use leveldb api on server? this would simplify project setup for smaller projects. It would seem that fetching data differently on front-end and back-end leads to more branches and therefore more maintenance work. Are there other benefits to this approach that I am not considering? I'm probably stating the obvious here, but then again, I am more of a "sophomore" of a dev.

**Comment by sethvincent** [comment]
I added an example showing use in the browser with [level-browserify](https://npmjs.com/level-browserify)

I suspect it won't be useful really to use level-model on both the server and client. I'm not really sure anymore that I would use this in the browser 😦. Unless it was a browser-only app that wanted a higher-level leveldb-style way to manage objects. But yeah, using this to sync between browser and server may get messy.
