### ISSUE TITLE
v3.0.0: functional API

### ISSUE THREAD

**Issue by sethvincent** [sethvincent/level-model#4]
For a while now I've considered refactoring this module to have a more functional API. This is one of the few modules I still work on that has a prototypal inheritance approach and I feel like the boilerplate doesn't have much benefit.

Here's a sketch of what I'm thinking:

```js
var memdb = require('memdb')
var levelModel = require('level-model')

var db = memdb()

var posts = levelModel(db, {
  modelName: 'posts',
  properties: {
    title: { type: 'string' },
    content: { type: 'string' },
  },
  indexKeys: ['title'],
  required: ['title', 'content']
  hooks: {
    beforeCreate: function beforeCreate (data) {
      return data
    }
  }
})
```

It only saves a little bit of boilerplate but I feel like it's worth it.

**Comment by bcomnes** [comment]
I like it better.  Does it make sense to add batch methods too?
